[project]
name = "original-performance-takehome"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[tool.ruff]
line-length = 200

[tool.ruff.format]
skip-magic-trailing-comma = true
